version: '3.5'
services:
  microservicio1:
    build: 
      context: ./app
      dockerfile: Dockerfile
    environment:
      - PORT=8000
    networks:
      - x_network
  microservicio2:
    build: 
      context: ./app
      dockerfile: Dockerfile
    environment:
      - PORT=8001
    networks:
      - x_network
  nginx:
    image: nginx:stable-alpine3.17-slim
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - microservicio1
      - microservicio2
    networks:
      - x_network
  
networks:
  x_network:
    driver: bridge
